version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache2
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - database
        volumes:
            - ./php/src:/var/www/html
        ports:
            - 8090:80
    database:
        container_name: database
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: soccer
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
            - "9905:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8082:80'
        restart: always
        environment:
            PMA_HOST: database
        depends_on:
            - database